.TH BINKD 8 "21 Jun 2012"
.SH NAME
binkd \- transfer files between two Fidonet systems over TCP/IP
.SH SYNOPSIS
.B binkd
.RB [ \-CcDipqrsvdmh ]
.RB [
.B \-P
.I node
]
.I config-file
.SH DESCRIPTION
.B Binkd
is a Fidonet mailer designed to operate
via TCP/IP networks. As a FTN-compatible internet daemon,
it makes possible efficient utilization
of TCP/IP protocol suite as a transport layer in
FTN-based (Fido Technology Network) networks.
.PP
.B Binkd
expects your spool for Fido-like networks to be in BSO
("Bink style outbound") or optionaly ASO ("Amiga style outbound") format.
BSO is also used by
.B ifmail
and
.B BinkleyTerm
mailers.

.SH OPTIONS
.TP
.BI \-C
.B Binkd
running with this option will reread the configuration file if
it is changed. The modification time of the configuration file
is checked every 60 seconds and on every incoming and outgoing
connection.
.TP
.BI \-c
Start client only. Normally
.B Binkd
starts both server and client.
.TP
.BI \-D
Run
.B Binkd
as a daemon (cannot be used for client-only mode).
.TP
.BI \-i
Run
.B Binkd
from
.B inetd.
.TP
.BI \-P
Poll a
.I node.
An empty *.ilo file in the outbound will be created,
which will force
.B Binkd
to connect to and to receive mail from the
.I node
(
.B Binkd
will also add "Node
.I node
* -" record to the table-of-nodes in
.B Binkd
\'s memory if there is no entry for the
.I node
in the configuration file).
.TP
.BI \-p
Start client manager, process polls, quit if the queue seems to
be empty after the next rescan. Implies
.BI \-c.
.TP
.BI \-q
Quiet mode. Turns off
.I printq,
.I conlog
and
.I percents
statements of configuration.
.TP
.BI \-r
Disable crypt traffic.
.TP
.BI \-s
Start server only. Normally
.B Binkd
starts both server and client.
.TP
.BI \-v
Be verbose.
.B Binkd \-v
will dump binkd's version and quit.
.TP
.BI \-vv
Dump version and compiled-in options.
.TP
.BI \-d
Dump parsed config and exit.
.TP
.BI \-m
Disable CRAM-MD5 authorization. Implies
.BI \-r.
.TP
.BI \-h
Print help message.

.SH SIGNALS
.TP
.BI SIGHUP
Causes
.B Binkd
to reload it's config.

.SH ENVIROMENT
.TP
.BI BINKD_LOG
log file name.
.B Binkd
uses this enviroment variable if the 
.BI logfile
token is not defined in the config file

.SH SEE ALSO
inetd(8)

Binkd FAQ, Binkd User Guide,
Binkd homepage http://binkd.grumbler.org,
http://www.corbina.net/~maloff/binkd/
ftp://happy.kiev.ua/pub/fidosoft/mailer/binkd/

.SH AUTHORS
Dima Maloff <maloff@tts.magadan.su> and others.

This manual page is based on "Binkd User Guide" by
nsoveiko@doe.carleton.ca (Nick Soveiko)

.SH "REPORTING BUGS"
Report bugs to <binkd-bugs@happy.kiev.ua>
