#!/bin/sh -e

# create new ftn user and group 64000.64000
if [ "$1" = configure ] && ! id ftn > /dev/null 2>&1; then
  adduser --system --home /var/spool/ftn --uid 64000 --group \
    --disabled-password --gecos Fidonet ftn
  chsh -s /bin/bash ftn
fi

if [ -x /usr/sbin/update-inetd ]; then
  update-inetd --add 'binkp\t\tstream\ttcp\tnowait\tftn\t/usr/sbin/tcpd\t/usr/sbin/binkd -i -s -q /etc/ftn/binkd.cfg'
fi

#DEBHELPER#

