binkd.obj: \
	"Config.h" \
	"assert.h" \
	"binlog.h" \
	"bsy.h" \
	"client.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"protocol.h" \
	"readcfg.h" \
	"sem.h" \
	"server.h" \
	"setpttl.h" \
	"sys.h" \
	"tools.h" \
	"nt\service.h" \
	"nt\win9x.h" \
	"nt\wsock.h"

binlog.obj: \
	"Config.h" \
	"assert.h" \
	"binlog.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

branch.obj: \
	"Config.h" \
	"getw.h" \
	"sys.h" \
	"tools.h"

bsy.obj: \
	"Config.h" \
	"assert.h" \
	"bsy.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"readdir.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

client.obj: \
	"Config.h" \
	"assert.h" \
	"bsy.h" \
	"client.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"https.h" \
	"iphdr.h" \
	"iptools.h" \
	"protocol.h" \
	"readcfg.h" \
	"sem.h" \
	"setpttl.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

crypt.obj: \
	"crypt.h"

exitproc.obj: \
	"Config.h" \
	"binlog.h" \
	"bsy.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"server.h" \
	"nt\wsock.h"

ftnaddr.obj: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

ftndom.obj: \
	"ftnaddr.h" \
	"ftndom.h" \
	"getw.h" \
	"tools.h"

ftnnode.obj: \
	"Config.h" \
	"assert.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

ftnq.obj: \
	"Config.h" \
	"assert.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"readdir.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

getw.obj: \
	"getw.h"

https.obj: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"https.h" \
	"iphdr.h" \
	"iptools.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

inbound.obj: \
	"Config.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"inbound.h" \
	"iphdr.h" \
	"protocol.h" \
	"readcfg.h" \
	"readdir.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

iptools.obj: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"iptools.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

md5b.obj: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"md5b.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"server.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

prothlp.obj: \
	"Config.h" \
	"assert.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

protocol.obj: \
	"Config.h" \
	"assert.h" \
	"binlog.h" \
	"bsy.h" \
	"common.h" \
	"crypt.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"inbound.h" \
	"iphdr.h" \
	"iptools.h" \
	"md5b.h" \
	"prothlp.h" \
	"protoco2.h" \
	"protocol.h" \
	"readcfg.h" \
	"readflo.h" \
	"sem.h" \
	"server.h" \
	"setpttl.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

readcfg.obj: \
	"Config.h" \
	"assert.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"iptools.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"readflo.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

readflo.obj: \
	"Config.h" \
	"assert.h" \
	"getw.h" \
	"readflo.h" \
	"tools.h"

run.obj: \
	"getw.h" \
	"run.h" \
	"tools.h"

server.obj: \
	"Config.h" \
	"assert.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"iptools.h" \
	"protocol.h" \
	"readcfg.h" \
	"sem.h" \
	"server.h" \
	"setpttl.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

setpttl.obj: \
	"setpttl.h"

srif.obj: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"run.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

tools.obj: \
	"Config.h" \
	"assert.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"readdir.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

xalloc.obj: \
	"getw.h" \
	"tools.h"

nt\WSock.obj: \
	"getw.h" \
	"tools.h"

nt\breaksig.obj: \
	"Config.h" \
	"binlog.h" \
	"bsy.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sys.h" \
	"tools.h" \
	"nt\win9x.h" \
	"nt\wsock.h"

nt\dirwin32.obj: \
	"nt\dirwin32.h"

nt\getfree.obj: \
	"config.h" \
	"getw.h" \
	"tools.h"

nt\sem.obj: \
	"getw.h" \
	"tools.h"

nt\service.obj: \
	"Config.h" \
	"getw.h" \
	"tools.h" \
	"nt\service.h"

nt\win9x.obj: \
	"Config.h" \
	"getw.h" \
	"tools.h" \
	"nt\win9x.h"

ntlm\des_enc.obj: \
	"ntlm\des.h" \
	"ntlm\des_locl.h" \
	"ntlm\ncbc_enc.c"

ntlm\ecb_enc.obj: \
	"ntlm\des.h" \
	"ntlm\des_locl.h" \
	"ntlm\spr.h"

ntlm\helpers.obj: \
	"iphdr.h" \
	"sys.h" \
	"nt\wsock.h" \
	"ntlm\des.h" \
	"ntlm\md4.h"

ntlm\md4_dgst.obj: \
	"ntlm\md32_com.h" \
	"ntlm\md4.h" \
	"ntlm\md4_locl.h"

ntlm\set_key.obj: \
	"ntlm\des.h" \
	"ntlm\des_locl.h"

