binkd.o: \
	"Config.h" \
	"assert.h" \
	"binlog.h" \
	"bsy.h" \
	"client.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"protocol.h" \
	"readcfg.h" \
	"sem.h" \
	"server.h" \
	"setpttl.h" \
	"sys.h" \
	"tools.h" \
	"nt\service.h" \
	"nt\win9x.h" \
	"nt\wsock.h"

binlog.o: \
	"Config.h" \
	"assert.h" \
	"binlog.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

branch.o: \
	"Config.h" \
	"getw.h" \
	"sys.h" \
	"tools.h"

bsy.o: \
	"Config.h" \
	"assert.h" \
	"bsy.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"readdir.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

client.o: \
	"Config.h" \
	"assert.h" \
	"bsy.h" \
	"client.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"https.h" \
	"iphdr.h" \
	"iptools.h" \
	"protocol.h" \
	"readcfg.h" \
	"sem.h" \
	"setpttl.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

crypt.o: \
	"crypt.h"

exitproc.o: \
	"Config.h" \
	"binlog.h" \
	"bsy.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"server.h" \
	"nt\wsock.h"

ftnaddr.o: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

ftndom.o: \
	"ftnaddr.h" \
	"ftndom.h" \
	"getw.h" \
	"tools.h"

ftnnode.o: \
	"Config.h" \
	"assert.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

ftnq.o: \
	"Config.h" \
	"assert.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"readdir.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

getw.o: \
	"getw.h"

https.o: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"https.h" \
	"iphdr.h" \
	"iptools.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

inbound.o: \
	"Config.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"inbound.h" \
	"iphdr.h" \
	"protocol.h" \
	"readcfg.h" \
	"readdir.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

iptools.o: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"iptools.h" \
	"readcfg.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

md5b.o: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"md5b.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"server.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

prothlp.o: \
	"Config.h" \
	"assert.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

protocol.o: \
	"Config.h" \
	"assert.h" \
	"binlog.h" \
	"bsy.h" \
	"common.h" \
	"crypt.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"inbound.h" \
	"iphdr.h" \
	"iptools.h" \
	"md5b.h" \
	"prothlp.h" \
	"protoco2.h" \
	"protocol.h" \
	"readcfg.h" \
	"readflo.h" \
	"sem.h" \
	"server.h" \
	"setpttl.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

readcfg.o: \
	"Config.h" \
	"assert.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"iptools.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"readflo.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

readflo.o: \
	"Config.h" \
	"assert.h" \
	"getw.h" \
	"readflo.h" \
	"tools.h"

run.o: \
	"getw.h" \
	"run.h" \
	"tools.h"

server.o: \
	"Config.h" \
	"assert.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"iptools.h" \
	"protocol.h" \
	"readcfg.h" \
	"sem.h" \
	"server.h" \
	"setpttl.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

setpttl.o: \
	"setpttl.h"

srif.o: \
	"Config.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"ftnq.h" \
	"getw.h" \
	"iphdr.h" \
	"prothlp.h" \
	"protoco2.h" \
	"readcfg.h" \
	"run.h" \
	"srif.h" \
	"sys.h" \
	"tools.h" \
	"nt\wsock.h"

tools.o: \
	"Config.h" \
	"assert.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"readdir.h" \
	"sem.h" \
	"sys.h" \
	"tools.h" \
	"nt\dirwin32.h" \
	"nt\wsock.h"

xalloc.o: \
	"getw.h" \
	"tools.h"

nt\WSock.o: \
	"getw.h" \
	"tools.h"

nt\breaksig.o: \
	"Config.h" \
	"binlog.h" \
	"bsy.h" \
	"common.h" \
	"ftnaddr.h" \
	"ftndom.h" \
	"ftnnode.h" \
	"getw.h" \
	"iphdr.h" \
	"readcfg.h" \
	"sys.h" \
	"tools.h" \
	"nt\win9x.h" \
	"nt\wsock.h"

nt\dirwin32.o: \
	"nt\dirwin32.h"

nt\getfree.o: \
	"config.h" \
	"getw.h" \
	"tools.h"

nt\sem.o: \
	"getw.h" \
	"tools.h"

nt\service.o: \
	"Config.h" \
	"getw.h" \
	"tools.h" \
	"nt\service.h"

nt\win9x.o: \
	"Config.h" \
	"getw.h" \
	"tools.h" \
	"nt\win9x.h"

ntlm\des_enc.o: \
	"ntlm\des.h" \
	"ntlm\des_locl.h" \
	"ntlm\ncbc_enc.c"

ntlm\ecb_enc.o: \
	"ntlm\des.h" \
	"ntlm\des_locl.h" \
	"ntlm\spr.h"

ntlm\helpers.o: \
	"iphdr.h" \
	"sys.h" \
	"nt\wsock.h" \
	"ntlm\des.h" \
	"ntlm\md4.h"

ntlm\md4_dgst.o: \
	"ntlm\md32_com.h" \
	"ntlm\md4.h" \
	"ntlm\md4_locl.h"

ntlm\set_key.o: \
	"ntlm\des.h" \
	"ntlm\des_locl.h"

