md5b.o: md5b.c iphdr.h sys.h protoco2.h btypes.h Config.h md5b.h tools.h \
 getw.h server.h
binkd.o: binkd.c readcfg.h Config.h btypes.h iphdr.h sys.h common.h \
 server.h client.h tools.h getw.h bsy.h protocol.h setpttl.h sem.h \
 ftnnode.h rfc2553.h srv_gai.h perlhooks.h prothlp.h protoco2.h \
 unix/daemonize.h confopt.h ftnaddr.h
readcfg.o: readcfg.c readcfg.h Config.h btypes.h iphdr.h sys.h common.h \
 sem.h tools.h getw.h protoco2.h srif.h iptools.h readflo.h ftnaddr.h \
 ftnnode.h ftndom.h ftnq.h perlhooks.h prothlp.h
tools.o: tools.c readcfg.h Config.h btypes.h iphdr.h sys.h common.h \
 tools.h getw.h readdir.h sem.h assert.h perlhooks.h prothlp.h protoco2.h
ftnaddr.o: ftnaddr.c tools.h getw.h btypes.h Config.h ftndom.h ftnaddr.h \
 iphdr.h sys.h
ftnq.o: ftnq.c readcfg.h Config.h btypes.h iphdr.h sys.h ftnq.h ftnnode.h \
 ftnaddr.h tools.h getw.h readdir.h perlhooks.h prothlp.h protoco2.h
client.o: client.c readcfg.h Config.h btypes.h iphdr.h sys.h client.h \
 ftnnode.h ftnaddr.h common.h iptools.h ftnq.h tools.h getw.h protocol.h \
 bsy.h assert.h setpttl.h sem.h perlhooks.h prothlp.h protoco2.h https.h \
 rfc2553.h srv_gai.h run.h
server.o: server.c iphdr.h sys.h readcfg.h Config.h btypes.h common.h \
 server.h iptools.h tools.h getw.h protocol.h assert.h setpttl.h sem.h \
 perlhooks.h prothlp.h protoco2.h rfc2553.h
protocol.o: protocol.c readcfg.h Config.h btypes.h iphdr.h sys.h common.h \
 protocol.h ftnaddr.h ftnnode.h ftndom.h ftnq.h iptools.h tools.h getw.h \
 bsy.h inbound.h protoco2.h srif.h readflo.h prothlp.h assert.h binlog.h \
 setpttl.h sem.h md5b.h crypt.h compress.h perlhooks.h rfc2553.h
bsy.o: bsy.c readcfg.h Config.h btypes.h iphdr.h sys.h bsy.h ftnaddr.h \
 ftndom.h sem.h tools.h getw.h assert.h readdir.h
inbound.o: inbound.c readcfg.h Config.h btypes.h iphdr.h sys.h inbound.h \
 protoco2.h common.h tools.h getw.h protocol.h readdir.h ftnaddr.h \
 ftnnode.h srif.h perlhooks.h prothlp.h
breaksig.o: breaksig.c sys.h common.h iphdr.h tools.h getw.h btypes.h \
 Config.h
branch.o: branch.c common.h iphdr.h sys.h tools.h getw.h btypes.h \
 Config.h
rename.o: unix/rename.c
getfree.o: unix/getfree.c
ftndom.o: ftndom.c ftndom.h btypes.h Config.h tools.h getw.h
ftnnode.o: ftnnode.c readcfg.h Config.h btypes.h iphdr.h sys.h ftnnode.h \
 ftnaddr.h sem.h tools.h getw.h ftnq.h rfc2553.h srv_gai.h
srif.o: srif.c readcfg.h Config.h btypes.h iphdr.h sys.h protoco2.h \
 srif.h ftnaddr.h tools.h getw.h run.h ftnq.h prothlp.h protocol.h \
 rfc2553.h
pmatch.o: pmatch.c
readflo.o: readflo.c Config.h tools.h getw.h btypes.h readflo.h
prothlp.o: prothlp.c prothlp.h btypes.h Config.h tools.h getw.h crypt.h
iptools.o: iptools.c iphdr.h sys.h Config.h common.h iptools.h tools.h \
 getw.h btypes.h sem.h rfc2553.h
rfc2553.o: rfc2553.c rfc2553.h iphdr.h sys.h sem.h
run.o: run.c run.h tools.h getw.h btypes.h Config.h
binlog.o: binlog.c readcfg.h Config.h btypes.h iphdr.h sys.h protoco2.h \
 binlog.h tools.h getw.h sem.h
exitproc.o: exitproc.c readcfg.h Config.h btypes.h iphdr.h sys.h common.h \
 ftnnode.h bsy.h tools.h getw.h sem.h server.h perlhooks.h prothlp.h \
 protoco2.h
getw.o: getw.c Config.h tools.h getw.h btypes.h
xalloc.o: xalloc.c tools.h getw.h btypes.h Config.h
crypt.o: crypt.c crypt.h
srv_gai.o: srv_gai.c srv_gai.h iphdr.h sys.h rfc2553.h
setpttl.o: unix/setpttl.c
daemonize.o: unix/daemonize.c tools.h getw.h btypes.h Config.h \
 unix/daemonize.h
ns_parse.o: unix/ns_parse.c
https.o: https.c readcfg.h Config.h btypes.h iphdr.h sys.h https.h \
 tools.h getw.h iptools.h sem.h ntlm/helpers.h rfc2553.h srv_gai.h
des_enc.o: ntlm/des_enc.c ntlm/des_locl.h ntlm/des.h ntlm/ncbc_enc.c
helpers.o: ntlm/helpers.c ntlm/../iphdr.h ntlm/../sys.h ntlm/des.h \
 ntlm/md4.h
ecb_enc.o: ntlm/ecb_enc.c ntlm/des_locl.h ntlm/des.h ntlm/spr.h
md4_dgst.o: ntlm/md4_dgst.c ntlm/md4_locl.h ntlm/md4.h ntlm/md32_com.h
set_key.o: ntlm/set_key.c ntlm/des_locl.h ntlm/des.h
perlhooks.o: perlhooks.c readcfg.h Config.h btypes.h iphdr.h sys.h \
 tools.h getw.h ftnaddr.h ftnq.h ftnnode.h readflo.h protoco2.h sem.h \
 protocol.h common.h perlhooks.h prothlp.h rfc2553.h
compress.o: compress.c zlibdl.h compress.h tools.h getw.h btypes.h \
 Config.h
